name: Gradle Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
    contents: read
    checks: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        gradle-version: ["8.8", "8.9"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle setup
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ matrix.gradle-version }}

      - name: Run Gradle Build
        run: ./gradlew build
        
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "**/build/test-results/test/TEST-*.xml"
          token: ${{ github.token }}
          summary: true
          detailed_summary: true
